### PR TITLE
Raise new custom exception class when API response is HTTP 423

### LINKED ISSUE #43: handle HTTP 423 locked response from pres cat
https://github.com/sul-dlss/preservation_catalog/pull/1608 adds the possibility that pres cat will reply with a 423.  pres client should `raise` a specific exception type for this situation, along the lines of `Preservation::Client::NotFoundError`

### PR DESCRIPTION
**Pull request by mjgiarlo**
Fixes #43

## Why was this change made?

To fix #43.

And, in so doing, bring more alignment with practices in other client gems (e.g., dor-services-client), such as testing using stubbed HTTP requests instead of testing a stubbed HTTP method.

## How was this change tested?

Unit tests.

## Which documentation and/or configurations were updated?

None.

### CODE REVIEW

File: lib/preservation/client/versioned_api_service.rb [hunk 1]
```diff
@@ -25,14 +25,14 @@ def get_json(path, object_id)
...
+        raise UnexpectedResponseError, errmsg
       rescue Faraday::ResourceNotFound
         errmsg = "#{object_id} not found in Preservation at #{connection.url_prefix}#{req_url}"
-        raise Preservation::Client::NotFoundError, errmsg
+        raise NotFoundError, errmsg
       rescue Faraday::Error => e
         errmsg = "Preservation::Client.#{caller_locations.first.label} for #{object_id} " \
           "got #{e.response[:status]} from Preservation at #{req_url}: #{e.response[:body]}"
-        raise Preservation::Client::UnexpectedResponseError, errmsg
+        raise UnexpectedResponseError, errmsg
```
Comment (mjgiarlo) [inline lib/preservation/client/versioned_api_service.rb:35]: If the code I added to this PR removed coverage of this one line... I would be surprised. I think CodeClimate is confused again.

**Comment by jmartin-sul** [comment]
thanks for the quick merge, beat me to it!

yeah, a new release would be great.

i think pres robots is the only thing that needs this at the moment -- there's WIP PR to get the primary location from pres cat for lookup use when needed, and i think we'll just end up building on that to always call pres cat, and to deal with the possible 4xx response codes as needed (see sul-dlss/preservation_robots#249 and sul-dlss/preservation_robots#239).

**Comment by mjgiarlo** [comment]
@ndushay @jmartin-sul 3.3.0 released.

Will upgrade presbots to 3.3.0 once that ticket is unblocked. Looks like it's waiting on one other in-progress PR that @aaron-collier and @jmartin-sul have worked on.
